### ISSUE TITLE
Exercise attachments

### ISSUE THREAD

**Issue by mjunker** [practice-buddy/the-practice-buddy#11]
Images should be displayed
Player for uploaded audio files 
Changing playback speed should be easy:
http://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_av_prop_playbackrate

**Comment by rolego** [comment]
shall we take care about storage size in any form? ...e.g. by compressing/resizing the attachments...?

**Comment by mjunker** [comment]
Yes probably. BSON with compressing the files might be the way to go:

The maximum BSON document size is 16 megabytes. The maximum document size helps ensure that a single document cannot use excessive amount of RAM or, during transmission, excessive amount of bandwidth. To store documents larger than the maximum size, MongoDB provides the GridFS API.
MongoDB Limits and Thresholds

docs.mongodb.com/manual/reference/limits

**Comment by mjunker** [comment]
http://valor-software.com/ng2-file-upload/

https://gist.github.com/aheckmann/2408370

http://stackoverflow.com/questions/13336324/converting-binary-strings-to-buffers-in-node-js

**Comment by mjunker** [comment]
First version for audio files merged. all other files can be downloaded at the moment. Will create more tasks for open points.
