### ISSUE TITLE
Setup (simple) build

### ISSUE THREAD

**Issue by rolego** [practice-buddy/the-practice-buddy#9]

**Comment by mjunker** [comment]
Done. See readme in server module.

Development:
gulp serve                      : Serve server. Restarts on changes.
gulp serveClient                : Serve client using angular-cli

Production (merges server and client to server dist):
gulp                            : Builds server and client to practice-buddy-server/dist so it can be run standalone using 'npm start'
gulp buildAllAndRunServer       : Builds server and client and starts server
